# Generated by Django 3.1.7 on 2021-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantuser',
            name='is_added_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
